"""Pydantic models for Agent B's structured output"""

from typing import List, Optional, Literal
from pydantic import BaseModel, Field


class Action(BaseModel):
    """Represents a single action in the task execution plan"""
    
    action_type: Literal[
        "navigate", 
        "click", 
        "type", 
        "wait", 
        "capture_screenshot", 
        "evaluate_state",
        "scroll",
        "select_option",
        "hover"
    ] = Field(..., description="Type of action to perform")
    
    target_description: str = Field(
        ..., 
        description="Natural language description of the element to interact with (e.g., 'Create Project button', 'project name input field')"
    )
    
    value: Optional[str] = Field(
        None, 
        description="Value to input (for type actions) or option to select (for select_option actions)"
    )
    
    expected_state_change: Optional[str] = Field(
        None, 
        description="What should happen after this action (e.g., 'modal opens', 'page navigates to project list')"
    )
    
    capture_after: bool = Field(
        False, 
        description="Whether to capture a screenshot after this action completes"
    )
    
    reasoning: Optional[str] = Field(
        None, 
        description="Why this action is necessary and how it contributes to the goal"
    )
    
    wait_conditions: Optional[List[str]] = Field(
        None,
        description="Conditions to wait for before proceeding (e.g., 'element visible', 'text appears')"
    )


class TaskPlan(BaseModel):
    """Complete task execution plan generated by Agent B"""
    
    goal: str = Field(..., description="The original natural language goal")
    
    steps: List[Action] = Field(..., description="Ordered sequence of actions to execute")
    
    assumptions: List[str] = Field(
        default_factory=list,
        description="Assumptions made about the website structure or user state"
    )
    
    potential_issues: List[str] = Field(
        default_factory=list,
        description="Potential edge cases, errors, or issues to watch for during execution"
    )
    
    success_criteria: List[str] = Field(
        default_factory=list,
        description="How to verify the task was completed successfully"
    )
    
    estimated_complexity: Literal["simple", "moderate", "complex"] = Field(
        "moderate",
        description="Estimated complexity of the task"
    )


